version: '3'
services:
  # Application Server
  app:
    build: ./app
    container_name: app
    tty: true
    environment: 
      - TZ=Asia/Tokyo
    volumes:
      - ./app/python_app:/var/www/uwsgi
      - socket:/tmp
    command: uwsgi --ini /var/www/uwsgi/app.ini
    depends_on:
      - db
  # Web Server
  web:
    image: nginx:1.21.6-alpine
    container_name: web
    ports:
      - 80:80
    restart: always
    environment: 
      - TZ=Asia/Tokyo
    volumes:
      - ./web/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/var/www/static
      - socket:/tmp
    depends_on:
      - app
  # Database
  db:
    image: mysql:8.0
    container_name: db
    ports: 
      - 3306:3306
    restart: always
    environment: 
      - TZ=Asia/Tokyo
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tectes_db
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=dev
    volumes: 
      - ./db/my.cnf:/etc/mysql/conf.d/my_config.cnf
      - ./db/mysql_init:/docker-entrypoint-initdb.d
  # phpMyAdmin
  pma:
    image: phpmyadmin:5.2.0
    container_name: pma
    ports: 
      - 8080:80
    restart: always
    environment: 
      - TZ=Asia/Tokyo
      - PMA_ARBITRARY=1
      - PMA_HOSTS=db
      - PMA_USER=root
      - PMA_PASSWORD=root
    volumes:
      - /sessions
    depends_on: 
      - db
volumes:
  # For WSGI Connection
  socket: